Part1 Homework
sdmnc/tk pull request #6
Opened 2023-09-14 12:58 UTC by sdmnc

2023-09-20 09:41 UTC, IvanCeban requested changes

2023-09-20 09:41 UTC, IvanCeban commented on index.html
> +    <script src = "script3.js">
Better pust the script in the head section

2023-09-20 09:41 UTC, IvanCeban commented on script3.js
> +        let name = company[i]
clean up the code. You're not using "name" variable

2023-09-20 09:41 UTC, IvanCeban commented on script3.js
> +        sortedArray.push(company[i])
this array is not sorted, so naming it "sortedArray" sounds confusing.

2023-09-20 09:41 UTC, IvanCeban commented on script3.js
> +for (let i = 0; i < company.length; i++) {
This loop seems redundant. I bet you can get rid of it and use only the loop from line 54

2023-09-21 11:07 UTC, sdmnc commented on script3.js
> +for (let i = 0; i < company.length; i++) {
Sorry I don't get it. I can manually remove const company = [["Dev", "QA", "HR", "Finance"], from object and after that I don't need that "for" is that what you mean?

2023-09-26 07:17 UTC, merged